# Generated by Django 5.1.1 on 2024-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='wastecollectionrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='wastecollectionrequest',
            name='booking_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='collector',
            name='email',
            field=models.EmailField(default='m@gmail.com', max_length=254),
        ),
    ]
