# Generated by Django 5.1.1 on 2024-11-25 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_wastecollectionrequest_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastecollectionrequest',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
